server {
    listen 80;
    server_name _;
    return 301 https://localhost;
}

server {
    listen 443 ssl default_server;
    server_name _;

    ssl_certificate /etc/nginx/certs/your_domain.crt;
    ssl_certificate_key /etc/nginx/certs/your_domain.key;

#     ssl_protocols TLSv1.2 TLSv1.3;
#     ssl_prefer_server_ciphers on;
#     ssl_ciphers 'ECDHE+AESGCM:CHACHA20';

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
