name: Docker Test

on:
  push:
    branches: ["feature/angular"]

permissions:
  contents: write

jobs:
  build_and_tag:
    uses: craigiswayne/ci-cd/.github/workflows/publish-docker-hub.yml@v1
    with:
      docker_hub_username: 'craigiswayne'
      docker_hub_repository: 'prototype'
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

# TODO
# remove secrets
# change $REPO_NAME -> ${{ env.REPO_NAME }}
# delete old tags,
# delete old releases
# cleanup docker repo

