name: Build and Release Docker Image

on:
  push:
    tags:
      - 'v*'

env:
  APP_NAME: 'prototype'

permissions:
  contents: write

jobs:
  build_and_containerize:
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/passing-information-between-jobs
    outputs:
      new_version: ${{steps.get_version.outputs.version}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: get_version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          # saving version to output storage
          echo "version=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: test_echos
        run: |
          echo "version from env = ${{ env.VERSION }}"
          echo "version from output = ${{ steps.get_version.outputs.VERSION }}"
          echo "version from output = ${{ get_version.outputs.VERSION }}"
          echo "version from output = ${{ outputs.VERSION }}"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.APP_NAME }}:${{ env.VERSION }} .
          docker tag ${{ env.APP_NAME }}:${{ env.VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:${{ env.VERSION }}

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{env.APP_NAME}}:${{ env.VERSION }}

  release:
    needs: build_and_containerize
    runs-on: ubuntu-latest

    steps:
      - env:
          VERSION: ${{needs.build_and_containerize.outputs.new_version}}
        run: echo "NEW VERSION = $VERSION"

      - name: 'test echos'
        run: "echo ENV VERSION: ${{env.VERSION}}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          make_latest: true
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
